server:
  port: 8002
  servlet:
    context-path: /payment

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      enabled: true

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    druid:
      validation-query: select 1

mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.longjing.springcloud.entities


eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://localhost:7002/eureka

  instance:
    instance-id: payment8002
    prefer-ip-address: true
    ##向服务端发送心跳时间间隔
    lease-expiration-duration-in-seconds: 1
    ##服务端收到服务上一次心跳等待时间，用于剔除服务
    lease-renewal-interval-in-seconds: 2
